Enable serving of index.html pages for requests ending in /
kotx/render pull request #12
Opened 2022-08-02 11:31 UTC by ncw

This then allow static web sites to be served properly from an R2
bucket.

2022-08-02 11:47 UTC, ncw commented
Just realised this is broken... Will upload a fixed version shortly!

2022-08-02 11:51 UTC, ncw commented
Fixed now!

2022-08-02 18:38 UTC, kotx requested changes
This looks good! All that's missing is adding `INDEX_FILE?: string` to the `Env` interface at the top of index.ts.
Might also need to check if `INDEX_FILE` is undefined instead of `""` as well.

2022-08-02 23:11 UTC, kotx commented
It might be nicer to have it support absolute paths like `/index.html`, but that might need a better name like `FALLBACK_PATH` or `FALLBACK_FILE`.

2022-08-03 11:37 UTC, ncw commented
> This looks good! All that's missing is adding `INDEX_FILE?: string` to the `Env` interface at the top of index.ts.

I missed that. I've never written any typescript before ;-)

> Might also need to check if `INDEX_FILE` is undefined instead of `""` as well.

Is this a good way?

```diff
@@ -36,7 +37,7 @@ export default {
     }
 
     const url = new URL(request.url);
-    if (env.INDEX_FILE === "" && url.pathname === "/") {
+    if (!env.INDEX_FILE && url.pathname === "/") {
       return new Response("OK");
     }
 
@@ -51,7 +52,7 @@ export default {
       var path = (env.PATH_PREFIX || "") + decodeURIComponent(url.pathname.substring(1));
 
       // Look for index file if asked for a directory
-      if (env.INDEX_FILE !== "" && (path.endsWith("/") || path === "")) {
+      if (env.INDEX_FILE && (path.endsWith("/") || path === "")) {
         path += env.INDEX_FILE;
       }
 ```

> It might be nicer to have it support absolute paths like `/index.html`, but that might need a better name like `FALLBACK_PATH` or `FALLBACK_FILE`.

I'm not sure I understand you here. An absolute path like `/index.html` would imply re-using the `/index.html` for every sub directory wouldn't it? I'm not sure how that would be used.

2022-08-03 17:46 UTC, kotx commented
> Is this a good way?
Yup, looks good!
> I'm not sure I understand you here. An absolute path like /index.html would imply re-using the /index.html for every sub directory wouldn't it? I'm not sure how that would be used.
Yeah, in hindsight an absolute path for subdirectory fallbacks wouldn't be very useful. We probably don't need that.

2022-08-04 11:28 UTC, ncw commented
I've updated that. PTAL :-)

2022-08-04 18:09 UTC, kotx commented
Just tested this and it's working! Thanks for the PR!

2022-08-04 18:09 UTC, kotx approved these changes

2022-08-04 18:09 UTC, merged

2022-08-04 22:28 UTC, ncw commented
Thank you for a great project 🙂