Add Jurisdiction Setting to Bucket Options
kotx/render pull request #44
Opened 2024-06-11 13:59 UTC by Enferium

This pull request adds the jurisdiction setting to the bucket options.

This prevents errors when accessing the bucket while publishing a worker to a jurisdiction-protected bucket.

2024-06-11 14:04 UTC, kotx requested changes
Typo: "buket" should be spelled "bucket"

2024-06-11 14:04 UTC, kotx commented
Thanks for the PR! Found a small typo, but otherwise these changes look good.

2024-06-11 17:14 UTC, Erisa approved these changes

2024-06-12 00:43 UTC, kotx approved these changes

2024-06-12 00:44 UTC, merged